# This file was generated by https://github.com/lionello/dub2nix v0.4.1
[ {
  fetch = {
    type = "git";
    url = "https://github.com/mutablefigment/botan-math/";
    ref = "v1.13.7";
    rev = "f4581c547825e3cc786192702f126302cbb4babc";
    sha256 = "0f2lav1d5kzfl4nrbr2c2228hn8k7xbicps9bwaj18x6366s2xzn";
    fetchSubmodules = false;
    date = "2023-12-02T14:58:02+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/ri64rdy38diz73644npig3ch12hj17rn-botan-math-f4581c5";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/etcimon/memutils.git";
    rev = "v1.0.9";
    sha256 = "08j9grn3l6gr275m392l0dfsx5ma6hs08gjfhh48hpy3v0bvb0ny";
    fetchSubmodules = false;
    date = "2023-03-02T15:19:28-05:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/glnf0ljd84mv6gzc9wgs1qq0vqqxvmzh-memutils";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/s-ludwig/taggedalgebraic.git";
    rev = "v0.11.22";
    sha256 = "02iy90nwy0zzy25hwdqbcgd0w0lwzramcvi3pgyljhq0w0vl5hkq";
    fetchSubmodules = false;
    date = "2021-05-20T21:00:02+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/p8id0qb13j8pjdczflj2x35w6v63q4cx-taggedalgebraic";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe-container.git";
    rev = "v1.0.1";
    sha256 = "0miynjmfzz340z3qw9mclaj6cyirzrpk528idr5yfmvl3jsi6wh8";
    fetchSubmodules = false;
    date = "2023-11-27T09:12:47+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/2vnn20q8k335h5k078yk4lrxkp4y63pd-vibe-container";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe.d.git";
    rev = "v0.9.7";
    sha256 = "1q4yvcaf36lmf29izg01x888v40snpwiph310nrlpr4gyhd834av";
    fetchSubmodules = false;
    date = "2023-08-29T13:24:09+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/7fq089i7zib7m9hxyl75mlfy264d9gnx-vibe.d";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe-core.git";
    rev = "v2.5.1";
    sha256 = "1g66vyn9hivy8rmsdl1xg1vz41csq5k91c04yvp4wqbil9cwgqdr";
    fetchSubmodules = false;
    date = "2023-11-24T17:25:20+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/iddq1amvzic8fn4xa2317ykmkrkdr51y-vibe-core";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/wilzbach/stdx-allocator.git";
    rev = "v2.77.5";
    sha256 = "03av8zp5p6vf6fg005xbmwnjfw96jyrr4dcj4m56c4a3vx7v72pk";
    fetchSubmodules = false;
    date = "2018-12-23T13:54:22+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/b3h25asfh205wzwjfzjf2k2kkccpp96k-stdx-allocator";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/mutablefigment/botan/";
    rev = "352f93a924b880ac80eb782aa65a45b68383644d";
    sha256 = "0n4k2cx7iaqlx9izl5zzrvm7p6n6hfj7a4hvyjx03d495i2g8yjf";
    fetchSubmodules = false;
    date = "2023-12-02T14:56:29+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/q3d4yn68kdrf1xv4lfdglyq7h3qk0523-botan-352f93a";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/rejectedsoftware/diet-ng.git";
    rev = "v1.8.1";
    sha256 = "11hrbvsxhipvcz9m1qlq92iaw0h35pzdy5rf7z8c4vx3hwjrnhni";
    fetchSubmodules = false;
    date = "2022-04-22T11:38:43+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/xziliy9ah3s3ah8mslnxsw47n4w6wkca-diet-ng";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/D-Programming-Deimos/openssl.git";
    rev = "v3.3.3";
    sha256 = "1634j4psp3qwgwhk2sa3jj6gvwv3i96hpg2wrdy9ihjhabnszn0f";
    fetchSubmodules = false;
    date = "2023-09-14T12:05:32+00:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/i3pgh154r80xvh4vsnl6srg6khmk5dg7-openssl";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/eventcore.git";
    rev = "v0.9.26";
    sha256 = "13bjs5v5l1387vi2ss4gvqlslhq33v9sn4pg7nis4r0wdw0zmlk1";
    fetchSubmodules = false;
    date = "2023-09-16T09:46:45+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/zy7ydasg4fwnim2m1mi4gzdg9l087wpb-eventcore";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/libmir/mir-linux-kernel.git";
    rev = "v1.0.1";
    sha256 = "1gcaavsni47352nvw9s41zkaswd582cafq3931i0zinhd9s3clag";
    fetchSubmodules = false;
    date = "2018-08-04T16:03:31+07:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/qz6axwci8kb1477j9dzgq85nscjfyvj1-mir-linux-kernel";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/etcimon/libasync.git";
    rev = "v0.8.6";
    sha256 = "1pbvlfxbp3p0ld0552dzdl4ng5939f84drjbcj8a7g199p1ih045";
    fetchSubmodules = false;
    date = "2020-02-22T09:07:54-05:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/6l82qf5nav5pkbvnrhcs5v9vwj5xycq3-libasync";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/bildhuus/deimos-openssl-static.git";
    rev = "v1.0.2+3.0.8";
    sha256 = "00wllmfrjpq5ln3zs9qcqf4kq2i6bqbjxwj0jnxwwz125kfm55sy";
    fetchSubmodules = false;
    date = "2023-02-24T13:23:37+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/g9shdkm450yg8c15rvqms8v09vql8z0l-deimos-openssl-static";
  };
} ]